
Digraph.o : Digraph.c Digraph.h List.h
	gcc -c -std=c99 -Wall Digraph.c

List.o : List.c List.h
	gcc -c -std=c99 -Wall List.c -g

clean :
	rm -f DigraphProperties DigraphProperties.o Digraph.o List.o
 
